POST http://localhost:3000/user/signup HTTP/1.1
Content-Type: application/json

{
    "email": "teste@ai",
    "password": "123456",
    "name": "teste"
}

### Login
POST http://localhost:3000/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "teste@ai",
    "password": "123456"
}

### Address
POST http://localhost:3000/address/signup HTTP/1.1
Content-Type: application/json

{
    "street": "testwwqe",
    "number": "123",
    "complement": "teste",
    "neighborhood": "teste"
}

###Card
POST http://localhost:3000/card/signup HTTP/1.1
Content-Type: application/json

{
    "cardNumber": "1234567891234567",
    "name": "teste",
    "validade": "12/2020",
    "cvv": "123",
    "value": "123"
}

### Order
POST http://localhost:3000/order/product HTTP/1.1
Content-Type: application/json

{
    "total": "123",
    "tamanho": "5e9f9b4b9d9b7e1f1c3b3b1b",
    "sabor": "abc",
    "ingredientes": ["arroz", "feijao", "batata"]
}

###List
GET http://localhost:3000/user/list HTTP/1.1
Content-Type: application/json
